# Welcome to Jekyll!
#

# Site settings
title: Ludwig Sound
description: Where past and present meets in Sound!
owner: Ludwig Sound
first_published: 2016 # if migrating another site, the year of your first publish
email: info@ludwigsound.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "/home/hannes/Jekyll_Theme_Test/spectral-master" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/ludwigsound
  # github: https://github.com/ludwigsound
  linkedin-square: https://linkedin.com/in/ludwigsound
  facebook-official: https://facebook.com/ludwigsound
  google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:info@ludwigsound.com
  #flickr:
  # instagram:
  #youtube-square:
  #spotify
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
